In [7]:
import os
import pandas as pd 
import numpy as np

In [8]:
train = pd.read_csv('./数据集/科创企业成长潜力模型/label/train_2.csv')
train.rename(columns={'label':'Y'}, inplace = True)
test = pd.read_csv('./数据集/科创企业成长潜力模型/upload.csv')

data_all = pd.concat((train[['ID','Y']],test[['ID','Y']]))

In [9]:
data_all

               ID    Y
0    corp_1001749  0.0
1    corp_1001231  0.0
2    corp_1004522  0.0
3    corp_1001738  1.0
4    corp_1003948  1.0
..            ...  ...
517  corp_1000552  NaN
518  corp_1001079  NaN
519  corp_1004730  NaN
520  corp_1000350  NaN
521  corp_1002156  NaN

[5022 rows x 2 columns]

In [10]:
folder_path = './数据集/科创企业成长潜力模型/data'  # 替换为你的文件夹路径
excel_files = [file for file in os.listdir(folder_path) if file.endswith('.xlsx') and file.startswith('政府支持') ]

In [11]:
len(excel_files)

25

In [12]:
excel_files

['政府支持_产品技术_再制造产品.xlsx',
 '政府支持_产品技术_升级和创新消费品.xlsx',
 '政府支持_产品技术_国家成熟适用节水技术推广.xlsx',
 '政府支持_产品技术_国家鼓励重大环保技术装备.xlsx',
 '政府支持_产品技术_水污染防治技术.xlsx',
 '政府支持_产品技术_绿色数据中心适用产品.xlsx',
 '政府支持_产品技术_能效之星产品.xlsx',
 '政府支持_产品技术_认定新技术新产品.xlsx',
 '政府支持_产品技术_首台重大技术装备.xlsx',
 '政府支持_培育项目_上市后备和培育企业.xlsx',
 '政府支持_培育项目_中国独角兽企业.xlsx',
 '政府支持_培育项目_政府支持其他培育企业.xlsx',
 '政府支持_培育项目_政府重点支持其他项目企业.xlsx',
 '政府支持_培育项目_政府重点试点项目企业.xlsx',
 '政府支持_培育项目_隐形冠军.xlsx',
 '政府支持_培育项目_雏鹰企业.xlsx',
 '政府支持_资金支持_中央引导地方科技发展资金支持项目.xlsx',
 '政府支持_资金支持_中小企业发展专项资金支持项目.xlsx',
 '政府支持_资金支持_产业结构调整专项资金支持项目.xlsx',
 '政府支持_资金支持_地方政府专项资金奖补企业.xlsx',
 '政府支持_资金支持_工业与信息化发展专项资金支持项目.xlsx',
 '政府支持_资金支持_工业转型升级专项资金支持项目.xlsx',
 '政府支持_资金支持_技术改造专项资金支持项目.xlsx',
 '政府支持_资金支持_科技创新券补贴企业.xlsx',
 '政府支持产品技术_政府认定各类领先产品.xlsx']

In [13]:
df1 = pd.read_excel('./数据集/科创企业成长潜力模型/data/'+excel_files[0],index_col=0)
df1.rename(columns={'企业名称':'ID','类型':'认定类型'}, inplace = True)
df1['年度'] = df1['发布日期'].apply(lambda x : x[:4]).astype('float')
df1 = df1[['ID','年度','认定类型','级别']]

In [14]:
df2 = pd.read_excel('./数据集/科创企业成长潜力模型/data/'+excel_files[5],index_col=0)
df2.rename(columns={'企业名称':'ID'}, inplace = True)
df2['年度'] = df2['发布日期'].apply(lambda x : x[:4]).astype('float')
df2 = df2[['ID','年度','级别']]

In [15]:
df3 = pd.read_excel('./数据集/科创企业成长潜力模型/data/'+excel_files[7],index_col=0)
df3.rename(columns={'企业名称':'ID','类型':'认定类型'}, inplace = True)
df3['年度'] = df3['发布日期'].apply(lambda x : x[:4]).astype('float')
df3 = df3[['ID','年度','认定类型','级别']]

In [16]:
df4 = pd.read_excel('./数据集/科创企业成长潜力模型/data/'+excel_files[8],index_col=0)
df4.rename(columns={'企业名称':'ID','类型':'认定类型'}, inplace = True)
df4['年度'] = df4['发布日期'].apply(lambda x : x[:4]).astype('float')
df4 = df4[['ID','年度','认定类型','级别']]

In [17]:
df5 = pd.read_excel('./数据集/科创企业成长潜力模型/data/'+excel_files[12],index_col=0)
df5.rename(columns={'企业名称':'ID'}, inplace = True)
df5 = df5[['ID','年度','级别']]

In [18]:
df6 = pd.read_excel('./数据集/科创企业成长潜力模型/data/'+excel_files[13],index_col=0)
df6.rename(columns={'企业名称':'ID'}, inplace = True)
df6 = df6[['ID','年度','级别']]

In [19]:
df7 = pd.read_excel('./数据集/科创企业成长潜力模型/data/'+excel_files[14],index_col=0)
df7.rename(columns={'企业名称':'ID'}, inplace = True)
df7 = df7[['ID','年度','级别']]

In [20]:
df8 = pd.read_excel('./数据集/科创企业成长潜力模型/data/'+excel_files[15],index_col=0)
df8.rename(columns={'公司现用名':'ID','类型':'认定类型'}, inplace = True)
df8 = df8[['ID','年度','认定类型']]

In [21]:
df9 = pd.read_excel('./数据集/科创企业成长潜力模型/data/'+excel_files[16],index_col=0)
df9.rename(columns={'企业名称':'ID','认定年度':'年度'}, inplace = True)
df9 = df9[['ID','年度','级别']]

In [22]:
df10 = pd.read_excel('./数据集/科创企业成长潜力模型/data/'+excel_files[17],index_col=0)
df10.rename(columns={'企业名称':'ID','等级':'级别','认定年度':'年度'}, inplace = True)
df10 = df10[['ID','年度','级别']]

In [23]:
df11 = pd.read_excel('./数据集/科创企业成长潜力模型/data/'+excel_files[18],index_col=0)
df11.rename(columns={'公司名':'ID','等级':'级别','认定年度':'年度'}, inplace = True)
df11 = df11[['ID','年度','级别']]

In [24]:
df12 = pd.read_excel('./数据集/科创企业成长潜力模型/data/'+excel_files[19],index_col=0)
df12.rename(columns={'企业名称':'ID','等级':'级别','认定年度':'年度'}, inplace = True)
df12 = df12[['ID','年度','级别']]

In [25]:
df13 = pd.read_excel('./数据集/科创企业成长潜力模型/data/'+excel_files[20],index_col=0)
df13.rename(columns={'企业名称':'ID','等级':'级别'}, inplace = True)
df13 = df13[['ID','年度','级别']]

In [26]:
df14 = pd.read_excel('./数据集/科创企业成长潜力模型/data/'+excel_files[21],index_col=0)
df14.rename(columns={'企业名称':'ID'}, inplace = True)
df14 = df14[['ID','年度','级别']]

In [27]:
df15 = pd.read_excel('./数据集/科创企业成长潜力模型/data/'+excel_files[22],index_col=0)
df15.rename(columns={'企业名称':'ID'}, inplace = True)
df15 = df15[['ID','年度','级别']]

In [28]:
df16 = pd.read_excel('./数据集/科创企业成长潜力模型/data/'+excel_files[23],index_col=0)
df16.rename(columns={'企业名称':'ID'}, inplace = True)
df16 = df16[['ID','年度','级别']]

In [29]:
df17 = pd.read_excel('./数据集/科创企业成长潜力模型/data/'+excel_files[24],index_col=0)
df17.rename(columns={'企业名称':'ID','类型':'认定类型'}, inplace = True)
df17['年度'] = df17['发布日期'].apply(lambda x : x[:4]).astype('float')
df17 = df17[['ID','年度','认定类型','级别']]

In [30]:
feats = pd.concat((df1,df2))
feats = pd.concat((feats,df3))
feats = pd.concat((feats,df4))
feats = pd.concat((feats,df5))
feats = pd.concat((feats,df6))
feats = pd.concat((feats,df7))
feats = pd.concat((feats,df8))
feats = pd.concat((feats,df9))
feats = pd.concat((feats,df10))
feats = pd.concat((feats,df11))
feats = pd.concat((feats,df12))
feats = pd.concat((feats,df13))
feats = pd.concat((feats,df14))
feats = pd.concat((feats,df15))
feats = pd.concat((feats,df16))
feats = pd.concat((feats,df17))

feats = feats.reset_index(drop=True)

In [27]:
features = feats.groupby('ID')['认定类型'].count().reset_index(drop=False)
features.rename(columns= {'认定类型':'科技奖项拼接个数'},inplace=True)
type_class = feats['认定类型'].unique()
type_class = type_class[~pd.isna(type_class)]
jibie_class = feats['级别'].unique() 
jibie_class = jibie_class[~pd.isna(jibie_class)]
for year in range(2018,2024):
    sub_data =feats[feats['年度']==year].groupby('ID')['认定类型'].count().reset_index(drop=False)
    sub_data.rename(columns= {'认定类型':f'{year}年_政府支持拼接个数'},inplace=True)
    features = features.merge(sub_data,how='left',on='ID')
    for cl in type_class:
        sub_data = feats[(feats['认定类型']== cl)&(feats['年度']==year)].groupby('ID')['级别'].count().reset_index(drop=False)
        sub_data.rename(columns={'级别':f'{year}年_政府支持拼接_{cl}_数量'},inplace=True)
        features = features.merge(sub_data,how='left',on='ID')
    for cl in jibie_class:
        sub_data = feats[(feats['级别']== cl)&(feats['年度']==year)].groupby('ID')['认定类型'].count().reset_index(drop=False)
        sub_data.rename(columns={'认定类型':f'{year}年_政府支持拼接_{cl}_数量'},inplace=True)
        features = features.merge(sub_data,how='left',on='ID')     
#df = df.merge(feature_yanfashili,how='left',on='ID')

In [28]:
features

,ID,科技奖项拼接个数,2018年_政府支持拼接个数,2018年_政府支持拼接_认定_数量,2018年_政府支持拼接_通过验收_数量,2018年_政府支持拼接_拟认定_数量,2018年_政府支持拼接_入选_数量,2018年_政府支持拼接_立项_数量,2018年_政府支持拼接_获奖_数量,2018年_政府支持拼接_评定_数量,...,2023年_政府支持拼接_拟补助_数量,2023年_政府支持拼接_通过审核_数量,2023年_政府支持拼接_拟支_数量,2023年_政府支持拼接_奖励_数量,2023年_政府支持拼接_培育_数量,2023年_政府支持拼接_推荐_数量,2023年_政府支持拼接_拟奖励_数量,2023年_政府支持拼接_国家级_数量,2023年_政府支持拼接_省级_数量,2023年_政府支持拼接_市级_数量
0,corp_1000001,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,corp_1000002,7,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,corp_1000003,2,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,corp_1000004,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,corp_1000005,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2856,corp_1005016,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2857,corp_1005017,1,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2858,corp_1005018,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2859,corp_1005020,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2860,corp_1005022,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
data_all = data_all.merge(features,how='left',on='ID')

In [30]:
data_all.to_csv('gov_cat.csv',index=0)

In [5]:
teach_cat = pd.read_csv('./数据集/科技拼接.csv')

In [35]:
feats = pd.concat((feats,teach_cat))

In [37]:
features = feats.groupby('ID')['认定类型'].count().reset_index(drop=False)
features.rename(columns= {'认定类型':'科技奖项拼接个数'},inplace=True)
type_class = feats['认定类型'].unique()
type_class = type_class[~pd.isna(type_class)]
jibie_class = feats['级别'].unique() 
jibie_class = jibie_class[~pd.isna(jibie_class)]
for year in range(2018,2024):
    sub_data =feats[feats['年度']==year].groupby('ID')['认定类型'].count().reset_index(drop=False)
    sub_data.rename(columns= {'认定类型':f'{year}年_政府科技拼接个数'},inplace=True)
    features = features.merge(sub_data,how='left',on='ID')
    for cl in type_class:
        sub_data = feats[(feats['认定类型']== cl)&(feats['年度']==year)].groupby('ID')['级别'].count().reset_index(drop=False)
        sub_data.rename(columns={'级别':f'{year}年_政府科技拼接_{cl}_数量'},inplace=True)
        features = features.merge(sub_data,how='left',on='ID')
    for cl in jibie_class:
        sub_data = feats[(feats['级别']== cl)&(feats['年度']==year)].groupby('ID')['认定类型'].count().reset_index(drop=False)
        sub_data.rename(columns={'认定类型':f'{year}年_政府科技拼接_{cl}_数量'},inplace=True)
        features = features.merge(sub_data,how='left',on='ID')

In [39]:
data_all = data_all.merge(features,how='left',on='ID')

In [40]:
data_all

,ID,Y,科技奖项拼接个数,2018年_政府科技拼接个数,2018年_政府科技拼接_认定_数量,2018年_政府科技拼接_通过验收_数量,2018年_政府科技拼接_拟认定_数量,2018年_政府科技拼接_入选_数量,2018年_政府科技拼接_立项_数量,2018年_政府科技拼接_获奖_数量,...,2023年_政府科技拼接_拟培育_数量,2023年_政府科技拼接_绩效考评合格_数量,2023年_政府科技拼接_认证_数量,2023年_政府科技拼接_保留_数量,2023年_政府科技拼接_拟支持_数量,2023年_政府科技拼接_支持_数量,2023年_政府科技拼接_拟推荐_数量,2023年_政府科技拼接_国家级_数量,2023年_政府科技拼接_省级_数量,2023年_政府科技拼接_市级_数量
0,corp_1001749,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,corp_1001231,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,corp_1004522,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,corp_1001738,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,corp_1003948,1.0,4.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5017,corp_1000552,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5018,corp_1001079,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5019,corp_1004730,NaN,9.0,2.0,0.0,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5020,corp_1000350,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5021,corp_1002156,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
data_all.to_csv('gov_tech_cat.csv',index=0)